# Largely inspired from (pointing to precise version)
# https://github.com/thejohnfreeman/project-template-python/tree/6d04c7b3b00460bb7473246096c52cc22d403226

# black support portion inspired from (pointing to precise version)
# https://github.com/python/black/blob/4a953b7241ce5f8bcac985fa33fdf3af4f42c0de/pyproject.toml

[tool.poetry]
name = "python-library-project-generator"
version = "0.0.0"
description = "Opinionated Python Library Project Template contains all the boilerplate you need to create a Python package."
license = "MIT"
homepage = "https://github.com/opinionated-digital-center/python-library-project-generator"
authors = ["Emmanuel Sciara <emmanuel.sciara@gmail.com>"]
keywords = ["python-library-project-generator"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    'Natural Language :: English',
    'Operating System :: POSIX',
    'Operating System :: MacOS :: MacOS X',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
]

[tool.poetry.dependencies]
python = "^3.6"
# Optional dependencies to be part of `test` extra
pytest = {version = "^6.2", optional = true}
PyHamcrest = {version = "^2.0", optional = true}
loguru = {version = "^0.4", optional = true}
# Optional dependencies to be part of `git` extra
gitpython = {version = "^3.1", optional = true}
# Optional dependencies to be part of `gitlab` extra
python-gitlab = {version = "^1.9", optional = true}
# Optional dependencies to be part of `lint` extra
flake8 = {version = "^4.0", optional = true}
flake8-bugbear = {version = "^19.8.0", optional = true}
pylint = {version = "^2.3", optional = true}
yapf = {version = "^0.27.0", optional = true}
# Optional dependencies to be part of `format` extra
isort = {version = "^4.3", optional = true}
seed-isort-config = {version = "^1.9.3", optional = true}
black = {version = "stable", optional = true, allow-prereleases = true}
# Optional dependencies to be part of `docs` extra
sphinx = {version = "^2.3.0", optional = true}
sphinx-autodoc-typehints = {version = "^1.10.3", optional = true}
sphinx-autobuild = {version = "^0.7.1", optional = true}
sphinx_rtd_theme = {version = "^0.4.3", optional = true}
# Optional dependencies to be part of `repl` extra
bpython = {version = "^0.18", optional = true}
# Non optional dependendies
#############################
# Add you dependencies here #
#############################
cookiecutter = "^1.7"

[tool.poetry.extras]
test = ["pytest", "PyHamcrest", "loguru"]
git = ["gitpython"]
gitlab = ["python-gitlab"]
lint = ["flake8", "flake8-bugbear", "pylint", "yapf"]
format = ["isort", "seed-isort-config", "black"]
docs= ["sphinx", "sphinx-autodoc-typehints", "sphinx-autobuild", "sphinx_rtd_theme"]
repl = ["bpython"]

[tool.isort]
# following black's doc for compatibility
# See https://github.com/psf/black#how-black-wraps-lines
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
force_grid_wrap = 0
line_length = 88
known_third_party = ["behave", "hamcrest", "pytest", "six", "toml"]

[tool.black]
line-length = 88
target_version = ["py38"]

[build-system]
requires = ["poetry==1.0.5"]
build-backend = "poetry.masonry.api"
