name: Test GitLab Pipeline

on:
  pull_request:
    paths:
      - '{{cookiecutter.project_slug}}/Makefile'
      - '{{cookiecutter.project_slug}}/.gitlab-ci.yml'

env:
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  gitlab-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install tools (Poetry)
        uses: Gr1N/setup-poetry@v4
      - name: Complete CI/CD setup
        run: make setup-cicd
      - name: Install GitLab pipeline test dependencies
        run: make install-gitlab-pipelines-test-dependencies
      - name: Run GitLab pipeline test
        env:
          PIPELINE_GIT_NAME: ${{ secrets.PIPELINE_GIT_NAME }}
          PIPELINE_GIT_PASSWORD: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.PIPELINE_GIT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.PIPELINE_GIT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.PIPELINE_GIT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.PIPELINE_GIT_EMAIL }}
        run: make test-gitlab-pipeline
